---
- name: Install AUR applications
  become: false
  kewlfft.aur.aur:
    name:
      - bitwarden-bin
      - google-chrome
      - visual-studio-code-bin
      - jetbrains-toolbox
      - slack-desktop-wayland
      - zoom
      - notion-app-electron
      - postman-bin
      - antigravity
    state: present
    use: paru

- name: Install refind-btrfs (snapshot boot entries for rEFInd)
  become: false
  kewlfft.aur.aur:
    name: refind-btrfs
    state: present
    use: paru
  when: bootloader == 'refind' and btrfs | bool