---
- name: Install applications
  community.general.pacman:
    name:
      - firefox
      - chromium
      - discord
      - thunderbird
      - gimp
      - inkscape
      - drawio-desktop
      - libreoffice-fresh
      - obsidian
      - vlc
    state: present